---
# Note: None of this will get run when "release == 'SECURITY'"
# We want to make sure packages get pulled, signed, and pushed before publicly
# pushing the security fix. Pushing tags will be done manually by a human.
- name: clear the previous remote tag
  command: git push origin :v{{ version }}
    chdir: ceph
  ignore_errors: yes
  when: clean

- name: push version commit to BRANCH-release branch
  command: git push origin {{ branch }}-release
    chdir: ceph

- name: "git checkout {{ branch }}"
  command: git checkout {{ branch }}
    chdir: ceph

- name: "merge {{ branch }}-release changes back into {{ branch }}"
  command: git merge {{ branch }}-release
    chdir: ceph
  
- name: push the newly created tag
  command: git push origin v{{ version }}
    chdir: ceph
